//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "realm")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub digest: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        super::account::Relation::Player.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::account::Relation::Realm.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
